### ISSUE TITLE
課表 Screenshot

### ISSUE THREAD

**Issue by z15r7** [nccu-app/schedule_issue#4]
### 檢查清單

- [X] 最新的行動政大依然沒辦法滿足我的願景 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)
- [X] 我確定這個想法還沒有被人提過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的想法的地方。除非他已經被close了，但你的期望無法達成
- [X] 我已經盡力闡述我的想法了，並且我知道如果我沒寫清楚，這個想法可能會消逝
- [X] 這份表單只為了一個目的而建。若文思泉湧，請開多個feature request
- [X] 我已經閱讀並了解貢獻指引了

### 你想要什麼功能？是因為有什麼困擾著你嗎？

將目前課表輸出為圖片並下載，以利使用者自行運用或分享

### 你想要我們怎麼解決？

將課表顯示區域輸出為符合手機螢幕尺寸的圖片檔並下載

### 這件事目前是有辦法可以完成的嗎？如果不行，你嘗試過什麼方法？

目前課表功能為 App 內頁框，螢幕截圖功能無法排除裝置通知欄、App 功能欄及其他內建於裝置或 App 的顯示組件。

**Comment by timsu92** [comment]
由於這項功能您可以截圖後裁掉其他項目即可，短時間內不會處理。
