### ISSUE TITLE
點擊課表空欄位新增自訂行程

### ISSUE THREAD

**Issue by z15r7** [nccu-app/schedule_issue#5]
### 檢查清單

- [X] 最新的行動政大依然沒辦法滿足我的願景 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)
- [X] 我確定這個想法還沒有被人提過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的想法的地方。除非他已經被close了，但你的期望無法達成
- [X] 我已經盡力闡述我的想法了，並且我知道如果我沒寫清楚，這個想法可能會消逝
- [X] 這份表單只為了一個目的而建。若文思泉湧，請開多個feature request
- [X] 我已經閱讀並了解貢獻指引了

### 你想要什麼功能？是因為有什麼困擾著你嗎？

點擊課表空欄位新增自訂行程。

### 你想要我們怎麼解決？

點擊或長按課表空欄位，跳出新增於該時段的自訂行程。

### 這件事目前是有辦法可以完成的嗎？如果不行，你嘗試過什麼方法？

N/A

**Comment by timsu92** [comment]
此項功能可以透過右下角的筆完成、新增行程
