### ISSUE TITLE
課表開啟

### ISSUE THREAD

**Issue by ZHIPINGAO** [nccu-app/schedule_issue#6]
### 檢查清單

- [X] 最新的行動政大依然沒辦法滿足我的願景 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)
- [X] 我確定這個想法還沒有被人提過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的想法的地方。除非他已經被close了，但你的期望無法達成
- [X] 我已經盡力闡述我的想法了，並且我知道如果我沒寫清楚，這個想法可能會消逝
- [X] 這份表單只為了一個目的而建。若文思泉湧，請開多個feature request
- [X] 我已經閱讀並了解貢獻指引了

### 你想要什麼功能？是因為有什麼困擾著你嗎？

要打開行動政大課表的時候一直需要重新登錄

### 你想要我們怎麼解決？

不需要一直重新登入

### 這件事目前是有辦法可以完成的嗎？如果不行，你嘗試過什麼方法？

可以，但非常麻煩

**Comment by timsu92** [comment]
想了解同學是怎麼使用的？因為我自己使用的時候並不會需要重複登入

**Comment by ZHIPINGAO** [comment]
就是我點進行動政大app，再點進課表，他就會跳出我要重新登入的輸入框。這樣應該算正常使用 嗎？

**Comment by timsu92** [comment]
是正常使用，並且我依然無法觸發需要重複登入的情況耶！

我試了3種方式：
1. 未登入直接進課表，登入一次後之後都可以直接使用
2. 先在「會員管理」登入，然後進課表都可以直接使用
3. 在已經登入的情況下開app，然後進課表都可以直接使用

想問同學完整的操作是甚麼呢？

**Comment by timsu92** [comment]
另外，您的系統是甚麼呢？是iOS? Android? 有版本號嗎？
如果是Android，應用程式版本至少是3.9.8嗎？iOS的話，目前最新版是2.8.2喔！

**Comment by ZHIPINGAO** [comment]
iOS
且已更新至2.8.2
但仍常常有要一直重新登入的情況

**Comment by timsu92** [comment]
我們這邊剛剛Android、iOS兩種機子都試過了，均沒有遇到這樣的情形。

請您再試試看重新安裝此應用程式。如果依然無法解決，麻煩您有空的時候到電算6F找楊琇媛，我們一起來研究這個問題！

**Comment by timsu92** [comment]
想跟您確認此問題是否已解決？
此外，如果沒有後續的動態，此問題將在數天後標完已解決

**Comment by timsu92** [comment]
由於許久沒有回覆，我們將關閉此issue。如果您仍有問題，歡迎再次詢問！
