### ISSUE TITLE
課表出現需要登入頁面

### ISSUE THREAD

**Issue by Rayyeahhhh** [nccu-app/schedule_issue#8]
### 檢查清單

- [X] 我可以在最新的行動政大中重現這個問題 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)
- [X] 我確定這個問題沒有被別人問過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的發現的地方。除非他已經被close了，問題卻仍存在
- [X] 我已經盡力完成這份問題表單了，並且我知道如果我沒寫完整，這個問題回報可能會被忽略
- [X] 這份問題表單僅有一項問題。若有多個問題，請開多個issue

### 你遇到什麼問題

課表出現需要登入的頁面，但輸入帳密只會顯示錯誤，即使已經登入或登出後再登入仍然無法解決

### 重現此問題的步驟

打開行動政大 選我的課表

### 螢幕截圖/錄影

![Screenshot_2024-10-01-08-33-12-24_8e734e89e3f36e46d3b8d9bd8a9e2835](https://github.com/user-attachments/assets/a25c221a-e9a6-41bd-9c17-908e61e40ce3)

### 剛剛沒有不小心把個資洩漏吧？

- [X] 沒有

### 你用什麼裝置

Android

**Comment by ltlnx** [comment]
@Rayyeahhhh 感謝回報。在我的行動政大及測試環境無法重現這個問題，想請問您的學號是多少，以便測試。
