### ISSUE TITLE
課表需要登入

### ISSUE THREAD

**Issue by lucycurryy** [nccu-app/schedule_issue#9]
### 檢查清單

- [X] 我可以在最新的行動政大中重現這個問題 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)
- [X] 我確定這個問題沒有被別人問過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的發現的地方。除非他已經被close了，問題卻仍存在
- [X] 我已經盡力完成這份問題表單了，並且我知道如果我沒寫完整，這個問題回報可能會被忽略
- [X] 這份問題表單僅有一項問題。若有多個問題，請開多個issue

### 你遇到什麼問題

App 課表需要登入inccu 帳號密碼 但一直登入不了（有確認帳號密碼都正確）目前是無法使用課表功能

### 重現此問題的步驟

某次打開課表功能就馬上跳出來說要登入

### 剛剛沒有不小心把個資洩漏吧？

- [X] 沒有

### 你用什麼裝置

IOS

**Comment by ltlnx** [comment]
@lucycurryy 感謝回報。在我的行動政大及測試環境無法重現這個問題，想請問您的學號是多少，以便測試。

**Comment by lucycurryy** [comment]
您好：謝謝您的回信我的學號是111507033再麻煩您好了！從我的iPhone傳送ltlnx ***@***.***> 於 2024年10月8日 10:29 寫道：﻿
@lucycurryy 感謝回報。在我的行動政大及測試環境無法重現這個問題，想請問您的學號是多少，以便測試。

**Comment by ltlnx** [comment]
@lucycurryy 抱歉這麼晚回覆 - 在這邊的測試機測試看起來沒有問題。因為之前課表的資料來源有些異動，但現在已處理完成，可以再測試一下您的行動政大看問題是否還在嗎？感謝！

**Comment by lucycurryy** [comment]
您好：感謝您的回信狀況已經解決非常謝謝您祝 順心從我的iPhone傳送ltlnx ***@***.***> 於 2024年10月13日 05:36 寫道：﻿
@lucycurryy 抱歉這麼晚回覆 - 在這邊的測試機測試看起來沒有問題。因為之前課表的資料來源有些異動，但現在已處理完成，可以再測試一下您的行動政大看問題是否還在嗎？感謝！
